from typing import Dict, Any, List
from datetime import datetime
from cyberai.core.session import PentestSession, Severity

SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH:     "🟠",
    Severity.MEDIUM:   "🟡",
    Severity.LOW:      "🟢",
    Severity.INFO:     "🔵",
}

def render_markdown(session: PentestSession, meta: Dict = {}) -> str:
    """Render full pentest report as Markdown"""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    findings = session.findings

    critical = [f for f in findings if f.severity == Severity.CRITICAL]
    high     = [f for f in findings if f.severity == Severity.HIGH]
    medium   = [f for f in findings if f.severity == Severity.MEDIUM]
    low      = [f for f in findings if f.severity == Severity.LOW]
    info     = [f for f in findings if f.severity == Severity.INFO]

    lines = [
        f"# CyberAI Pentest Report",
        f"",
        f"**Target:** `{session.target}`  ",
        f"**Session ID:** `{session.id}`  ",
        f"**Generated:** {now}  ",
        f"**Status:** {session.state.value.upper()}",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {len(critical)} |",
        f"| 🟠 High     | {len(high)} |",
        f"| 🟡 Medium   | {len(medium)} |",
        f"| 🟢 Low      | {len(low)} |",
        f"| 🔵 Info     | {len(info)} |",
        f"| **Total**   | **{len(findings)}** |",
        f"",
        f"---",
        f"",
        f"## Findings",
        f"",
    ]

    for i, finding in enumerate(findings, 1):
        emoji = SEVERITY_EMOJI.get(finding.severity, "⚪")
        lines += [
            f"### {i}. {emoji} {finding.title}",
            f"",
            f"**Severity:** {finding.severity.value}  ",
            f"**Target:** `{finding.target or session.target}`  ",
            f"**ID:** `{finding.id}`  ",
            f"**Timestamp:** {finding.timestamp}",
            f"",
            f"{finding.description}",
            f"",
        ]
        if finding.cve_ids:
            lines.append(f"**CVEs:** {', '.join(finding.cve_ids)}")
            lines.append("")
        if finding.evidence:
            lines.append("**Evidence:**")
            for ev in finding.evidence:
                if ev:
                    lines.append(f"- `{ev}`")
            lines.append("")
        lines.append("---")
        lines.append("")

    # Attack paths section
    attack_paths = session.knowledge_base.get("exploit.attack_paths", {})
    paths = attack_paths.get("attack_paths", [])
    if paths:
        lines += ["## Attack Paths", ""]
        for j, path in enumerate(paths, 1):
            lines += [
                f"### Path {j}: {path.get('title', 'Unknown')}",
                f"",
                f"**Likelihood:** {path.get('likelihood', 'N/A')}  ",
                f"**Impact:** {path.get('impact', 'N/A')}  ",
                f"**MITRE:** {', '.join(path.get('mitre_tactics', []))}",
                f"",
                f"**Steps:**",
            ]
            for step in path.get("steps", []):
                lines.append(f"1. {step}")
            lines.append("")
            if path.get("cves_used"):
                lines.append(f"**CVEs:** {', '.join(path['cves_used'])}")
            lines += ["", "---", ""]

    lines += [
        "## Agent Activity Log",
        "",
        f"Total agent actions: {len(session.agent_log)}",
        "",
        "```",
    ]
    for entry in session.agent_log[-10:]:  # Last 10 entries
        lines.append(
            f"[{entry['timestamp']}] {entry['agent']} → {entry['action']}"
        )
    lines += ["```", "", "*Generated by CyberAI*"]

    return "\n".join(lines)
