from datetime import datetime
from cyberai.core.session import PentestSession, Severity

SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH:     "🟠",
    Severity.MEDIUM:   "🟡",
    Severity.LOW:      "🟢",
    Severity.INFO:     "🔵",
}

def render_markdown(session: PentestSession) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    findings = session.findings

    critical = [f for f in findings if f.severity == Severity.CRITICAL]
    high     = [f for f in findings if f.severity == Severity.HIGH]
    medium   = [f for f in findings if f.severity == Severity.MEDIUM]
    low      = [f for f in findings if f.severity == Severity.LOW]
    info     = [f for f in findings if f.severity == Severity.INFO]

    lines = [
        "# CyberAI Pentest Report",
        "",
        f"**Target:** `{session.target}`  ",
        f"**Session ID:** `{session.session_id}`  ",
        f"**Generated:** {now}  ",
        f"**Status:** {session.state.value.upper()}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {len(critical)} |",
        f"| 🟠 High     | {len(high)} |",
        f"| 🟡 Medium   | {len(medium)} |",
        f"| 🟢 Low      | {len(low)} |",
        f"| 🔵 Info     | {len(info)} |",
        f"| **Total**   | **{len(findings)}** |",
        "",
        "---",
        "",
        "## Findings",
        "",
    ]

    for i, finding in enumerate(findings, 1):
        emoji = SEVERITY_EMOJI.get(finding.severity, "⚪")
        lines += [
            f"### {i}. {emoji} {finding.title}",
            "",
            f"**Severity:** {finding.severity.value}  ",
            f"**Target:** `{session.target}`  ",
            f"**Agent:** {finding.agent}  ",
            f"**Timestamp:** {finding.timestamp}",
            "",
            f"{finding.description}",
            "",
        ]
        if finding.cve:
            lines.append(f"**CVE:** `{finding.cve}`")
            lines.append("")
        if finding.data:
            lines.append(f"**Data:** `{finding.data}`")
            lines.append("")
        lines += ["---", ""]

    lines += [
        "## Summary",
        "",
        f"Total findings: {len(findings)}",
        f"Critical: {len(critical)} | High: {len(high)} | Medium: {len(medium)}",
        "",
        "*Generated by CyberAI*",
    ]

    return "\n".join(lines)
